import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./custom.css";
import { SurvivalProvider } from "./context/survivalContext";

export const metadata: Metadata = {
  title: "Survival Nexus",
  icons: {
    icon: "/images/zombie-hand-white.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SurvivalProvider>{children}</SurvivalProvider>
      </body>
    </html>
  );
}
